apiVersion: skaffold/v1beta11
kind: Config
# Enforce SKaffold to use Jib
build: 
# Generated artifact
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VER}}"
  artifacts:
    - image: asia.gcr.io/my-gcp101/simpletest
     
# Use jibMaven
      jibMaven: 
       args:
       - -DskipTests
       

# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/simpletest.yaml

profiles:
  - name: local
    build:
      local:
         push: false
      artifacts:
       - image: simpletest
         jibMaven: 
           args:
           - -DskipTests
    deploy:    
      kubectl:
       manifests:
         - k8s/minikube/*.yaml
    
  