apiVersion: skaffold/v1beta11
kind: Config
# Enforce SKaffold to use Jib
build:
  local:
    push: false
# Generated artifact
  artifacts:
    - image: simpletest
# Use jibMaven
      jibMaven: {}
# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/simpletest.yml